# docker-compose.yml
version: '3'

services:
    solana:
        image: solanalabs/solana:beta
        ports:
            - 8899:8899
            - 8900:8900
    vault:
        image: vault:latest
        environment: 
            VAULT_DEV_ROOT_TOKEN_ID: zoints
            VAULT_ADDR: http://127.0.0.1:8200
        ports:
            - 8200:8200

